fschmid_dev_sso_service:
  cookies:
    shared_cookie_domain: '%env(FSCHMID_SHARED_COOKIE_DOMAIN)%'
  user_provider:
    url: '%env(FSCHMID_USER_PROVIDER_URL)%'
    user: App\\Entity\\User
  routes:
    login_success: app_home
    login_failure: app_home
    logout: app_logout
